Add significant efficiencies for zettel casts

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -19,14 +19,81 @@ test -z "$GITUSER" && echo "GITUSER not set." && exit 1
 # for the existance of the default directory and create the folder if
 # necessary. This not only allows for customization of the parent
 # directory via $ZETDIR, but also allows for compatibility with the
-# KEG/KN toolset.
+# KEG/KN toolset. This directory is expected to contain one or more
+# subdirectories, each of which is usually a git repository that directly
+# matches the name of the multicall executable (ex: $ZETDIR/zet).
 
-test -d "$HOME/.local/share/zet" && pdir="$HOME/.local/share/zet"
-test -d "$KN" && pdir="$KN"
-test -d "$ZETDIR" && pdir="$ZETDIR"
+test -d "$HOME/.local/share/zet" && ZETDIR="$HOME/.local/share/zet"
+test -d "$KN" && ZETDIR="$KN"
 
 EXE=${0##*/}
 test -z "$EXE" && echo "Could not determine name of executable." && exit 1
+DIR="$ZETDIR/$EXE"
+
+# ------------------------- complete context -------------------------
+
+declare -a COMMANDS=(usage a add q query text d dir e edit id urlencode titles last title body before after ids v video for)
+
+if [[ -n $COMP_LINE ]]; then
+    for c in "${COMMANDS[@]}"; do
+        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
+    done
+    exit
+fi
+
+# ----------------------------- commands -----------------------------
+
+_usage() {
+    local cmds="${COMMANDS[@]}"
+    printf "usage: ${0##*/} (${cmds// /|})\n"
+}
+
+_video() {
+  local zet="$1"
+  local IFS=$'\n'
+  if [[ -z $zet ]]; then
+    while read -r line; do
+      _video "$line"
+    done
+    return 0
+  fi
+  local dir="$(_d)/$1"
+  local readme="$dir/README.md"
+  [[ ! -r $readme ]] && echo "<not found>" && return 1
+  while read -r line; do
+    [[ $line =~ ^📺\  ]] && echo "${line#* }" && return 0
+  done < "$readme"
+  return 1
+}
+
+_v() { _video "$@"; }
+
+_urlencode() {
+  local string="$*"
+  if [[ -z $string ]]; then
+    local IFS=$'\n'
+    while read -r line; do
+      _urlencode "$line"
+    done
+  fi
+  local strlen=${#string}
+  local encoded=""
+  local pos c o
+  for ((pos = 0; pos < strlen; pos++)); do
+    c=${string:$pos:1}
+    case "$c" in
+    [-_.~a-zA-Z0-9]) o="${c}" ;;
+    *) printf -v o '%%%02x' "'$c" ;;
+    esac
+    encoded+="${o}"
+  done
+  echo "${encoded}"
+}
+
+_id() { date -u +%Y%m%d%H%M%S; }
+
+_dir() { [[ -d $DIR ]] && echo "$DIR"; }
+_d() { _dir "$@"; }
 
 # Add creates a Zettelkasten repo entry with an isosec unique directory
 # name within the $KN/$EXE parent directory. Whatever the effective name
@@ -37,13 +104,13 @@ test -z "$EXE" && echo "Could not determine name of executable." && exit 1
 # commiting and pushing to main/master is allowed (which is usually fine
 # for knowledge repos).
 
-add() {
-  test ! -d "$pdir/$EXE" && echo "Directory not found: $pdir/$EXE" && exit 1
-  dir="$pdir/$EXE/$(isosec)"
+_add() {
+  local dir="$(_d)/$(_id)"
+  local readme="$dir/README.md"
   mkdir -p "$dir"
-  ${EDITOR:-vim} "$dir/README.md"
+  "${EDITOR:-vim}" "$readme"
   cd "$dir"
-  test ! -e "$dir/README.md" && rmdir "$dir"
+  # TODO bail if file is zero length
   line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
   test -n "$line"
   echo "Adding: $line"
@@ -51,47 +118,117 @@ add() {
   git commit -m "$line"
   git push
 }
+_a() { _add "$@"; }
 
-titles() {
-  local -a zets=($(find "$pdir/$EXE" -maxdepth 2 -type d -path '*/20*'|sort ))
+_edit() {
+  local dir="$(_d)/$1"
+  local readme="$dir/README.md"
+  [[ ! -r $readme ]] && echo "Not found." && return 1
+  "${EDITOR:-vim}" "$readme"
+  # TODO prompt for "save" (git commit)
+}
+_e() { _edit "$@"; }
 
+_titles() {
+  local dir=$(_d)
+  local -a zets=($(find "$dir" -maxdepth 2 -type d -path '*/20*'|sort ))
   local IFS=$'\n'
+  local buf
   for i in ${zets[@]}; do
     [[ -r "$i/README.md" ]] || continue
-    echo "${i##*/}" $(head -1 "$i/README.md")
+    local title=$(head -1 "$i/README.md")
+    [[ $title =~ ^#\  ]] || title="<untitled>"
+    title="${title#*# }"
+    buf="$buf${i##*/} ${title#*# }  "$'\n'
   done
+  pandoc -t plain --wrap=none <<< "$buf"
 }
 
 _last() {
-  local line=$(titles | tail -1)
-  echo "* [${line##*\# }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
+  local line=$(_titles | tail -1)
+  echo "* [${line#* }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
 }
 
-totxt() {
-  local zet="$1"
-  dir="$pdir/$EXE/$zet"
-  [[ -r $dir/README.md ]] || return
-  txt < $dir/README.md
+_text() {
+  local dir="$(_d)/$1"
+  local readme="$dir/README.md"
+  [[ -r $readme ]] || return 1
+  local pandoc=$(command -v pandoc)
+  [[ -z $pandoc ]] && echo "'$EXE text' requires pandoc" && return 1
+  pandoc -t plain --wrap=none < "$readme"
 }
 
-query() {
-  test -z "$1" && echo "Missing search query." && exit 1
-  type urlencode >/dev/null 2>&1
+_title() {
+  local dir="$(_d)/$1"
+  [[ -d $dir ]] || return 1
+  local readme="$dir/README.md"
+  read -r title < $readme
+  [[ ! $title =~ ^#\  ]] && return 1
+  pandoc -t plain --wrap=none <<< "${title#\# }"
+}
+
+_body() {
+  local dir="$(_d)/$1"
+  [[ -d $dir ]] || return 1
+  local readme="$dir/README.md"
+  local buf=$(<$readme)
+  local eol=$'\n'
+  [[ $buf =~ ^\#\  ]] && buf=${buf#*$eol$eol} 
+  buf=${buf#📺 *$eol$eol}
+  pandoc -t plain --wrap=none <<< "$buf"
+}
+
+_query() {
+  [[ -z "$1" ]] && echo "Missing search query." && return 1
   term="$*"
-  it="https://github.com/$GITUSER/$EXE/search?q=$(urlencode $term)"
+  it="https://github.com/$GITUSER/$EXE/search?q=$(_urlencode $term)"
   echo "[$term]: <$it>"
-  type wee >/dev/null 2>&1 || return 0
-  exec wee "$it"
+  local chat=$(command -v chat)
+  [[ -z $chat ]] && return 0
+  exec chat "$it"
+}
+_q() { _query "$@"; }
+
+_ids() {
+  while read -r line; do
+    echo "${line##*/}"
+  done < <(find "$(_d)" -maxdepth 2 -type d -path '*/20*'| sort)
 }
 
-case "$1" in
-add | "") add ;;
-titles) titles ;;
-totxt) shift; totxt "$@";;
-last) shift; _last "$@";;
-q | query)
-  shift
-  query "$@"
-  ;;
-*) echo Unsupported. ;;
-esac
+_before() {
+  local id=$1
+  local prev
+  while read -r cur; do
+    (( cur > $id )) && break
+    prev=$cur
+  done < <(_ids)
+  echo $prev
+}
+
+_for() {
+  local mkv="$1"
+  [[ $mkv =~ - ]] && mkv=$(mkv2isosec "$1")
+  local id=${mkv##*/}
+  id=${id%.mkv}
+  zet before $id
+}
+
+_after() {
+  local id=$1
+  while read -r cur; do
+    (( cur > $id )) && break
+  done < <(_ids)
+  echo $cur
+}
+
+# ---------------------------- delegation ----------------------------
+
+declare cmd="$1"; shift
+for c in "${COMMANDS[@]}"; do
+    if [[ $c == "$cmd" ]]; then
+      "_$cmd" "$@"
+      exit $?
+    fi
+done
+
+_usage "$@"
