Fix urlencode and add _filter to zet commands

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -2,13 +2,13 @@
 # shellcheck disable=SC2016
 set -e
 
-test -z "$GITUSER" && echo "GITUSER not set." && exit 1
-
-test -d "$HOME/.local/share/zet" && ZETDIR="$HOME/.local/share/zet"
-test -d "$KN" && ZETDIR="$KN"
+: "${GITUSER:=$USER}"
+: "${GITBRANCH:=main}"
+: "${ZETDIR:=$HOME/.local/share/zet}"
+[[ -n "$KN" ]] && ZETDIR="$KN"
 
 EXE=${0##*/}
-test -z "$EXE" && echo "Could not determine name of executable." && exit 1
+[[ -z "$EXE" ]] && echo "Could not determine name of executable." && exit 1
 DIR="$ZETDIR/$EXE"
 
 declare -A help
@@ -21,12 +21,24 @@ repos.
 
 ## Usage
 
+In place of `<zet>` the word `last` can be used instead as well as any
+path to the `README.md` file or the "zet cast" YouTube video identifier
+(the id or URL, if it has one).
+
 ```
 zet usage
 zet help [<command>]
 zet (a|add)           - create new zettel dir and open with editor
-zet after <zetid>     - print id of first zettel after <zetid>
-zet before <zetid>    - print id of first zettel before <zetid>
+zet after <zettel>    - print id of first zettel after <zetid>
+zet before <zettel>   - print id of first zettel before <zetid>
+zet body <zettel>     - print zettel body
+zet commit <zettel>   - git commit zettel with title as message
+zet (d|dir)           - print zettelkasten repo directory path
+zet (each)            - iterate over each zettel
+
+
+zet title <zetid>     - print zettel title
+
 ```
 
 ## Dependencies
@@ -87,6 +99,9 @@ x_usage() {
 }
 
 help[each]='
+
+**Not yet implemented.**
+
 The `each` command reads the arguments as a template for a command to be
 passed to the command line. The syntax of the template uses Go templates
 (as popularized by Kubernetes). The following values can be wrapped in
@@ -129,19 +144,18 @@ x_each() {
   done
 }
 
+help[grep]='
+The `grep` command simply a shortcut for `zet each grep "$@"` running
+the system grep on all the main zettel README.md files passing the
+arguments as-is to the grep command (-P for PCRE, etc.)
+'
 
-# Grep is simply a shortcut for `zet each grep "$@"` running the system
-# grep on all the main zettel README.md files passing the arguments
-# as-is to the grep command (-P for PRCE, etc.)
-
-x_grep() {
-  x_each grep "$@"
-}
+x_grep() { x_each grep "$@"; }
 
 x_open() {
   local zetid="$1"
   [[ -z "$zetid" || $zetid = last ]] && zetid=$(x_last)
-  open "https://github.com/rwxrob/zet/tree/main/$zetid"
+  open "https://github.com/$GITUSER/zet/tree/main/$zetid"
 }
 
 _make_html() {
@@ -151,6 +165,10 @@ _make_html() {
   pandoc -s --metadata title="$title" \
     -o "/tmp/$name-help.html" <<< "${help[$name]}"
 }
+
+help[help]='
+The `help` command prints help information for this script or the
+specific command (first argument).'
 
 x_help() { 
   local name=${1:-main} 
@@ -164,15 +182,7 @@ x_help() {
 }
 
 x_commit() {
-
-  # recurse if called as filter
-  local IFS=$'\n'
-  if [[ -z "$1" ]]; then
-    while read -r line; do
-      x_commit "$line"
-    done
-    return 0
-  fi
+  _filter "$@"
 
   # if no zet, bail
   local dir
@@ -195,15 +205,7 @@ x_commit() {
 }
 
 x_video() {
-
-  # recurse if called as filter
-  local IFS=$'\n'
-  if [[ -z "$1" ]]; then
-    while read -r line; do
-      x_video "$line"
-    done
-    return 0
-  fi
+  _filter "$@"
 
   # accept zet or yt ids  
   local zetid ytid changed
@@ -258,13 +260,8 @@ x_video() {
 x_v() { x_video "$@"; }
 
 x_urlencode() {
+  _filter "$@"
   local string="$*"
-  if [[ -z $string ]]; then
-    local IFS=$'\n'
-    while read -r line; do
-      x_urlencode "$line"
-    done
-  fi
   local strlen=${#string}
   local encoded=""
   local pos c o
@@ -272,14 +269,14 @@ x_urlencode() {
     c=${string:$pos:1}
     case "$c" in
     [-_.~a-zA-Z0-9]) o="${c}" ;;
-    *) printf -v o '%%%02x' "'$c" ;;
+    *) printf -v o '%%%02x' "'$c'" ;;
     esac
     encoded+="${o}"
   done
   echo "${encoded}"
 }
 
-x_id() { date -u +%Y%m%d%H%M%S; }
+x_isosec() { date -u +%Y%m%d%H%M%S; }
 
 x_dir() { [[ -d $DIR ]] && echo "$DIR"; }
 x_d() { x_dir; }
@@ -297,12 +294,12 @@ help[a]='The `a` command is a short form of `add`.'
 
 x_add() {
   local dir readme
-  dir="$(x_d)/$(x_id)"
+  dir="$(x_d)/$(x_isosec)"
   readme="$dir/README.md"
   mkdir -p "$dir"
   "${EDITOR:-vim}" "$readme"
   cd "$dir"
-  # TODO bail if file is zero length
+  [[ -s "$dir/README.md" ]] || return 1
   line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
   test -n "$line"
   echo "Adding: $line"
@@ -329,7 +326,6 @@ x_edit() {
   local readme="$dir/README.md"
   [[ ! -r $readme ]] && echo "Not found." && return 1
   "${EDITOR:-vim}" "$readme"
-  # TODO prompt for "save" (git commit)
 }
 x_e() { x_edit "$@"; }
 
@@ -354,10 +350,11 @@ x_last() {
   mapfile titles < <(x_titles)
   last=${#titles[@]}
   echo "${titles[$last-1]%% *}"
-  #echo "* [${line#* }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
+  #echo "* [${line#* }](https://github.com/$GITUSER/zet/tree/main/${line%% *})"
 }
 
 x_text() {
+  _filter "$@"
   local dir readme
   dir="$(x_d)/$1"
   readme="$dir/README.md"
@@ -368,6 +365,7 @@ x_text() {
 }
 
 x_title() {
+  _filter "$@"
   local dir readme title
   dir="$(x_d)/$1"
   [[ -d $dir ]] || return 1
@@ -378,6 +376,7 @@ x_title() {
 }
 
 x_body() {
+  _filter "$@"
   local dir readme title buf eol
   dir="$(x_d)/$1"
   [[ -d $dir ]] || return 1
@@ -390,6 +389,7 @@ x_body() {
 }
 
 x_query() {
+  _filter "$@"
   [[ -z "$1" ]] && echo "Missing search query." && return 1
   term="$*"
   it="https://github.com/$GITUSER/$EXE/search?q=$(x_urlencode "$term")"
@@ -404,12 +404,13 @@ x_ids() {
   done < <(find "$(x_d)" -maxdepth 2 -type d -path '*/2*'| sort)
 }
 
-help[after]='
-The `after` command prints the zet id of the first zettel immediately
-following the one passed as an argument. '
-
+help[before]='
+The `before` command prints the zet id of the first zettel immediately
+preceeding the one passed as an argument. This command can be called as
+a filter.'
 
 x_before() {
+  _filter "$@"
   local prev
   while read -r cur; do
     (( cur > id )) && break
@@ -419,6 +420,7 @@ x_before() {
 }
 
 x_for() {
+  _filter "$@"
   local mkv id
   mkv="$1"
   [[ $mkv == last ]] && mkv=$(mkvlast)
@@ -430,43 +432,72 @@ x_for() {
 
 help[after]='
 The `after` command prints the zet id of the first zettel immediately
-following the one passed as an argument. '
+following the one passed as an argument. This command may be called as
+a filter.'
 
 x_after() {
-  local id
-  if [[ -z "$1" ]]; then
-    local IFS=$'\n'
-    while read -r line; do
-      x_after "$line"
-    done
-  fi
-  id="$1"
+  _filter "$@"
+  local id="$1"
   while read -r cur; do
     (( cur > id )) && break
   done < <(x_ids)
   echo "$cur"
 }
 
+help[id]='
+The `id` command prints the isosec identifier derived from the passed
+argument:
+
+1. If already an isosec and zet exists, print argument
+2. If `last`, delegate to `zet last`
+3. If isosec match found (`2[0-9]{13,}`), print match
+4. If YouTube id or URL, delegate to `yt zet`
+
+This command may be called as a filter.
+'
+
+x_id() {
+    _filter "$@"
+    echo would id
+}
+
 # --------------------- completion and delegation --------------------
 
-while read -r line; do
+_filter(){
+  (( $# > 0 )) && return 0
+  while IFS= read -ra args; do
+    "${FUNCNAME[1]}" "${args[@]}"
+  done
+}
+
+while IFS= read -r line; do
     [[ $line =~ ^declare\ -f\ x_ ]] || continue
     COMMANDS+=( "${line##declare -f x_}" )
 done < <(declare -F)
 
 if [[ -n $COMP_LINE ]]; then
+    line=${COMP_LINE#* }
     for c in "${COMMANDS[@]}"; do
-        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
+        [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
     done
     exit
 fi
 
-declare cmd="$1"; shift
+EXE="${0##*/}"
 for c in "${COMMANDS[@]}"; do
-    if [[ $c == "$cmd" ]]; then
-        "x_$cmd" "$@"
+    if [[ $c == "$EXE" ]]; then
+        "x_$EXE" "$@"
+        exit $?
+    fi
+done
+
+CMD="$1"; shift
+for c in "${COMMANDS[@]}"; do
+    if [[ $c == "$CMD" ]]; then
+        "x_$CMD" "$@"
         exit $?
     fi
 done
 
 x_usage "$@"
+
